services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${APP_POSTGRES_USER?}
      - POSTGRES_PASSWORD=${APP_POSTGRES_PASSWORD?}
      - POSTGRES_DB=${APP_POSTGRES_DB?}
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

  app:
    image: hack_template
    restart: on-failure:5
    command: python -m hack_template
    environment:
      - APP_DB_DSN=${APP_DB_DSN?}
      - APP_REST_PORT=8080
      - APP_REST_HOST=0.0.0.0
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_db: