name: Build and push images

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  DOCKERHUB_IMAGE: hack-template

jobs:
  checking:
    name: Check repository
    uses: ./.github/workflows/checks.yml

  build_and_push_docker:
    name: Build and push AMD64 and ARM64 images
    needs: checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Determine image tag
        id: image_tag
        run: |
          if [ "${{ github.ref }}" != "refs/heads/master" ]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: ./
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE }}:${{ env.TAG }}